name: Build HACS Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create HACS zip
        run: zip -r ha-mqtt_sensors.zip custom_components/ha_mqtt_sensors

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hacs-build
          path: ha-mqtt_sensors.zip

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ha-mqtt_sensors.zip
